### ISSUE TITLE
Train data of different sizes

### ISSUE THREAD

**Issue by IvanZidov** [Sentdex/BCI#6]
Hi Sentdex
I have been loading training data and I found a problem.
You said that the data is of size 250,16,60 but I have found some examples where data is 
500,16,60 or 375,16,60 or 750,16,60

**Comment by moznpan** [comment]
Hey @IvanZidov.  @Sentdex addressed this in his readme. 

> Each file is targeted to be 10 seconds long, which, at 25 iter/sec gives us, the 250 (though **you should not depend/assume all files will be exactly 250 long**). Then you have the number of channels (16), and then 60 values, for up to 60Hz. 

I just took the first :250 of each array on load to keep things simple. If you wanted to go all out, you could just window the data in chunks of 250. And, since you know what the sample rate and start times are, you could calculate the resulting timestamps for the window offsets yourself, if needed.
